Add module to auto-write SQL Alchemy models from data
th-bunratta/MovieAwardOntologyMAO pull request #5
Opened 2020-11-14 06:46 UTC by MaiMee1

### Effects
- `extended_csv.py`: Move method `select_not_null` to `utils.py` for reuse

**New requirements**
- pandas

### Tests
None yet

2020-11-14 06:48 UTC, MaiMee1 commented
Force push to remove wrongly committed temporary files 😅

2020-11-14 08:05 UTC, th-bunratta requested changes
Nothing much to say as some are imported modules. Keep up good work!

2020-11-14 08:05 UTC, th-bunratta commented on tests/test_autowrite.py
> +    def test_something(self):
What's `test_something()`? More descriptive name?

2020-11-14 08:10 UTC, MaiMee1 commented on tests/test_autowrite.py
> +    def test_something(self):
Great. Need to add tests for the new feature.

2020-11-15 03:48 UTC, MaiMee1 commented
Force pushed to take in test path bug fix (1645e0f) from master

2020-11-15 07:16 UTC, MaiMee1 commented on tests/test_autowrite.py
> +    def test_something(self):
Tests added

2020-11-16 16:10 UTC, th-bunratta approved these changes
Looks good. Better merge the PR real soon to keep up with the pending works.

2020-11-16 16:10 UTC, th-bunratta commented on sa_autowrite/hint.py
> +class DeclaredModel(ABC):
This class is used for type hinting, isn't it?

2020-11-16 16:10 UTC, th-bunratta commented on sa_autowrite/model.py
> +class Table:
Is this an abstraction of the real SA Table implementation used in **autowrite** scripts?

2020-11-16 17:16 UTC, NutthanichN approved these changes
I ran the sample code from `sa_autowrite/README.md` (after solved this [`numpy`'s `RuntimeError`](https://stackoverflow.com/questions/64729944/runtimeerror-the-current-numpy-installation-fails-to-pass-a-sanity-check-due-to)). It worked fine and shoud be ready to be merged.

2020-11-16 17:24 UTC, MaiMee1 commented
> I ran the sample code from `sa_autowrite/README.md` (after solved this [`numpy`'s `RuntimeError`](https://stackoverflow.com/questions/64729944/runtimeerror-the-current-numpy-installation-fails-to-pass-a-sanity-check-due-to)). It worked fine and shoud be ready to be merged.

😰 Seems like we should be careful about our environment and packages

2020-11-16 17:24 UTC, MaiMee1 commented on sa_autowrite/hint.py
> +class DeclaredModel(ABC):
Yes. Wanted some hints for the code, but not sure if it's correct or not. Shouldn't affect the program adversely tho.

2020-11-16 17:26 UTC, MaiMee1 commented on sa_autowrite/model.py
> +class Table:
More like a store of the data needed to write one such model. Not really related to SA's table, but just using the same name.

2020-11-16 17:27 UTC, MaiMee1 commented
Thanks for reviewing. I'll merge it now and open a new PR for further improvements for dealing with large data.

2020-11-16 17:28 UTC, merged