Generate .md file from .yaml ontology specs
th-bunratta/MovieAwardOntologyMAO pull request #8
Opened 2020-11-15 16:03 UTC by NutthanichN

Generate .md file from .yaml ontology specs with python scripts.

**Note: This script doesn't support class hierarchy and property hierarchy generation**

2020-11-15 16:05 UTC, MaiMee1 commented
I can't request you to review lol @NutthanichN 
Should've opened the PR myself :joy:
Oh well

2020-11-15 16:15 UTC, NutthanichN commented
> 
> 
> I can't request you to review lol @NutthanichN
> Should've opened the PR myself 😂
> Oh well

I did review it btw lol
Everything works ok, though we should add more tests later.

2020-11-16 17:37 UTC, MaiMee1 commented
I refactored the code somewhat. Should be a lot more readable and a lot less redundant. Haven't added any tests except doctests for `get_md_list()` yet though.

2020-11-17 06:09 UTC, th-bunratta requested changes
There seems to have some code integrable with `ontogen` in this branch. Maybe add some more unit tests?

2020-11-17 06:09 UTC, th-bunratta commented on yamd/pretty_label.py
> +def get_language_from_code(language_code: str) -> str:
Maybe support for more languages

2020-11-18 01:15 UTC, MaiMee1 commented
Latest force push was for editing the message to better reflect the changes. I'll try to wait like half an hour after I commit to push next time so that I don't have much of these "fix typos"-esque force pushes.

2020-11-18 02:05 UTC, MaiMee1 commented on yamd/pretty_label.py
> +def get_language_from_code(language_code: str) -> str:
Tests using the .yaml and .md files added in 008c336. Test still fails because of specification changes, but maybe @NutthanichN or @Wijantra can take care of that?

2020-11-18 02:06 UTC, MaiMee1 commented
Tests using the .yaml and .md files added in 008c336. Test still fails because of specification changes, but maybe @NutthanichN or @Wijantra can take care of that?

2020-11-18 02:07 UTC, MaiMee1 commented on yamd/pretty_label.py
> +def get_language_from_code(language_code: str) -> str:
You seem to already be doing this in `ontogen`?

2020-11-18 02:18 UTC, NutthanichN commented
> 
> 
> Tests using the .yaml and .md files added in [008c336](https://github.com/th-bunratta/MovieAwardOntologyMAO/commit/008c336a4d58263c847ebc771261c906034659d9). Test still fails because of specification changes, but maybe @NutthanichN or @Wijantra can take care of that?

I'll look at them.

2020-11-22 13:34 UTC, merged